In [1]:
# Import libraries
import os
import csv
import gzip
import pickle
import numpy as np
import pandas as pd
import gseapy as gp
import seaborn as sns
import matplotlib.pyplot as plt
from datasets import load_dataset
from pxblat import Server, Client #pxblat==0.3.6

/Users/vivianschu/opt/anaconda3/envs/scgpt/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
# Define model (finetuned or pretrained)
model = 'random_init-2'
dataset = 'pancreas'

In [3]:
# Define the path to the directory containing the pickle files
base = "/Users/vivianschu/Documents/MBP/Lab/Genomic Interpretability/scgpt_attn_results/test/FINAL_LRP-attention"
data_dir = os.path.join(base, dataset, model)

pkl_files = [
    'examples_scores_attention_layer0.p',
    'examples_scores_attention_layer1.p',
    'examples_scores_attention_layer2.p',
    'examples_scores_attention_layer3.p',
    'examples_scores_attention_layer4.p',
    'examples_scores_attention_layer5.p',
    'examples_scores_attention_layer6.p',
    'examples_scores_attention_layer7.p',
    'examples_scores_attention_layer8.p',
    'examples_scores_attention_layer9.p',
    'examples_scores_attention_layer10.p',
    'examples_scores_attention_layer11.p',
]

In [4]:
# Load all pickle files into memory
layers_data = []
for file_name in pkl_files:
    file_path = os.path.join(data_dir, file_name)
    with open(file_path, 'rb') as f:
        layers_data.append(pickle.load(f))

# Assuming all layers have the same number of heads and all heads have the same number of cells
num_layers = len(layers_data)
num_heads = len(layers_data[0])
num_cells = len(layers_data[0][0])
num_genes = len(layers_data[0][0][0][0]) - 1  # Assuming each cell contains data for the same number of genes

print('Check Data:', num_layers, num_heads, num_cells, num_genes)

Check Data: 12 8 499 499

In [5]:
# Open compiled_cells.csv
compiled_cells_path = os.path.join(data_dir, 'compiled_cells.csv')
compiled_cells = pd.read_csv(compiled_cells_path, sep=';')

compiled_cells.head()

,gene_sequence,label,expression,layer0_head0,layer0_head1,layer0_head2,layer0_head3,layer0_head4,layer0_head5,layer0_head6,...,layer11_head2,layer11_head3,layer11_head4,layer11_head5,layer11_head6,layer11_head7,position_first_third,position_middle_third,position_last_third,position
0,"<cls>,TXLNA,ATP2A3,ZNF141,CCDC141,SLC25A37,STO...",5,"0.0,48.0,33.0,25.0,5.0,3.0,10.0,28.0,5.0,29.0,...","0.0023745133,0.0032477628,0.003589545,0.003814...","0.0041318787,0.0053796424,0.0041540335,0.00306...","0.0056217974,0.0031721308,0.005039241,0.004776...","0.0034448185,0.0032406966,0.0040769065,0.00487...","0.0038653233,0.0041617695,0.0020131315,0.00385...","0.003914756,0.0034802882,0.005446018,0.0034722...","0.0042973505,0.0035008143,0.0028890239,0.00347...",...,"0.0029499263,0.0024055955,0.002513074,0.002640...","0.0025008207,0.0026199492,0.002841934,0.002556...","0.00444397,0.0023903793,0.0024260334,0.0031343...","0.002858873,0.0026262312,0.0025715895,0.002385...","0.0030605097,0.002257548,0.0024005037,0.002462...","0.0050789197,0.0029359038,0.003200909,0.003342...","1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,1..."
1,"<cls>,DSG2,TMEM144,TNFRSF1B,FKBP11,MUC20,DCN,A...",5,"0.0,39.0,7.0,19.0,6.0,17.0,7.0,19.0,26.0,6.0,4...","0.0022430576,0.0024487586,0.003219843,0.003661...","0.004013164,0.0031627351,0.0036624381,0.003953...","0.0042283423,0.0031852438,0.004393687,0.002575...","0.0034300121,0.0023620245,0.0043808324,0.00346...","0.0032802566,0.0028360444,0.0044557275,0.00289...","0.004048269,0.0047665904,0.0038825262,0.003081...","0.0042852582,0.0031577605,0.0056061805,0.00359...",...,"0.0029518714,0.002717198,0.0027214303,0.002277...","0.0027387682,0.0030519136,0.0027144155,0.00291...","0.0033776136,0.002504747,0.0026376792,0.002287...","0.0028611864,0.0027302948,0.002847653,0.002169...","0.0032267557,0.0026814435,0.0026326487,0.00242...","0.004437197,0.0030190656,0.0034014382,0.002829...","1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,1..."
2,"<cls>,CNN2,LRAT,ACTN1,PLD6,PHLDB2,PIGA,CES2,MY...",5,"0.0,27.0,20.0,39.0,5.0,7.0,3.0,11.0,12.0,1.0,3...","0.0022238698,0.0040896675,0.004484682,0.002118...","0.0039243894,0.0040566986,0.0026453421,0.00478...","0.0048712324,0.0034570356,0.0030926508,0.00369...","0.003476348,0.0037290629,0.0028929042,0.004210...","0.003399026,0.0025909895,0.0042975056,0.004100...","0.004021946,0.002352441,0.0031674122,0.0027053...","0.0031837898,0.0027910753,0.0021618963,0.00399...",...,"0.0027702104,0.002785568,0.002417999,0.0025976...","0.0025693388,0.0023259071,0.002565366,0.002743...","0.0035079145,0.0025205663,0.002532903,0.002934...","0.0025086715,0.0025067604,0.0024263477,0.00244...","0.002859213,0.002560808,0.0023383668,0.0023868...","0.004376093,0.0029561946,0.0025371308,0.003263...","1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,1..."
3,"<cls>,NINJ1,TNS3,SLC6A6,PGM2L1,CABYR,SLC3A1,SE...",5,"0.0,42.0,19.0,39.0,20.0,17.0,14.0,33.0,21.0,37...","0.0020445194,0.0031070835,0.0025515305,0.00327...","0.0040934836,0.0028073455,0.0034256505,0.00244...","0.0043800664,0.0029222732,0.0025062195,0.00437...","0.0034533436,0.0025593678,0.003978598,0.002954...","0.0038189043,0.0032943436,0.002777985,0.003936...","0.0036355853,0.0033676857,0.00409,0.0038118216...","0.0043353783,0.0040053073,0.002787665,0.002944...",...,"0.0028078433,0.002296238,0.0024589011,0.002672...","0.002720637,0.002522182,0.0024271347,0.0025703...","0.0036673287,0.0026340187,0.002360998,0.002149...","0.0025690747,0.0023017398,0.0025352214,0.00236...","0.0029805924,0.002354244,0.0025769223,0.002633...","0.004431809,0.0034919812,0.0031394286,0.003201...","1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,1..."
4,"<cls>,TMBIM1,SNAI1,LMCD1,ZNF347,KCNJ2,NID1,UPK...",2,"0.0,5.0,23.0,42.0,26.0,39.0,28.0,28.0,28.0,16....","0.0021203735,0.002208613,0.0047930344,0.004826...","0.0040604477,0.0039716368,0.00493733,0.0033131...","0.005657586,0.003112157,0.0040237918,0.0037283...","0.003414135,0.0037594072,0.004144798,0.0034618...","0.003272853,0.0038072,0.0030302322,0.004112403...","0.0044797715,0.004235163,0.0032671287,0.003604...","0.0043147453,0.0030068154,0.002950847,0.006144...",...,"0.0027981123,0.002369921,0.0031287852,0.002464...","0.0027399058,0.0028127648,0.0025866495,0.00272...","0.004089777,0.0025660961,0.0024449755,0.002961...","0.002994695,0.002675196,0.0029123412,0.0023097...","0.0028690922,0.0030195368,0.0022447829,0.00248...","0.004281797,0.0027155657,0.002892087,0.0029022...","1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,1..."

In [6]:
# Open compiled_cells_features.csv
cells_features_path = os.path.join(data_dir, 'compiled_cells-features.csv')
cells_features = pd.read_csv(cells_features_path, sep=';')

cells_features.head()

,gene_sequence,label,expression,layer0_head0,layer0_head1,layer0_head2,layer0_head3,layer0_head4,layer0_head5,layer0_head6,...,HP_X_LINKED_DOMINANT_INHERITANCE,HP_X_LINKED_RECESSIVE_INHERITANCE,HP_YELLOW_BROWN_DISCOLORATION_OF_THE_TEETH,HP_YELLOW_WHITE_LESIONS_OF_THE_MACULA,HP_YELLOW_WHITE_LESIONS_OF_THE_RETINA,HP_YOUNG_ADULT_ONSET,HP_Y_LINKED_INHERITANCE,HP_Y_SHAPED_METACARPALS,HP_ZOLLINGER_ELLISON_SYNDROME,HP_ZONULAR_CATARACT
0,"<cls>,TXLNA,ATP2A3,ZNF141,CCDC141,SLC25A37,STO...",5,"0.0,48.0,33.0,25.0,5.0,3.0,10.0,28.0,5.0,29.0,...","0.0023745133,0.0032477628,0.003589545,0.003814...","0.0041318787,0.0053796424,0.0041540335,0.00306...","0.0056217974,0.0031721308,0.005039241,0.004776...","0.0034448185,0.0032406966,0.0040769065,0.00487...","0.0038653233,0.0041617695,0.0020131315,0.00385...","0.003914756,0.0034802882,0.005446018,0.0034722...","0.0042973505,0.0035008143,0.0028890239,0.00347...",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,..."
1,"<cls>,DSG2,TMEM144,TNFRSF1B,FKBP11,MUC20,DCN,A...",5,"0.0,39.0,7.0,19.0,6.0,17.0,7.0,19.0,26.0,6.0,4...","0.0022430576,0.0024487586,0.003219843,0.003661...","0.004013164,0.0031627351,0.0036624381,0.003953...","0.0042283423,0.0031852438,0.004393687,0.002575...","0.0034300121,0.0023620245,0.0043808324,0.00346...","0.0032802566,0.0028360444,0.0044557275,0.00289...","0.004048269,0.0047665904,0.0038825262,0.003081...","0.0042852582,0.0031577605,0.0056061805,0.00359...",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,..."
2,"<cls>,CNN2,LRAT,ACTN1,PLD6,PHLDB2,PIGA,CES2,MY...",5,"0.0,27.0,20.0,39.0,5.0,7.0,3.0,11.0,12.0,1.0,3...","0.0022238698,0.0040896675,0.004484682,0.002118...","0.0039243894,0.0040566986,0.0026453421,0.00478...","0.0048712324,0.0034570356,0.0030926508,0.00369...","0.003476348,0.0037290629,0.0028929042,0.004210...","0.003399026,0.0025909895,0.0042975056,0.004100...","0.004021946,0.002352441,0.0031674122,0.0027053...","0.0031837898,0.0027910753,0.0021618963,0.00399...",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,..."
3,"<cls>,NINJ1,TNS3,SLC6A6,PGM2L1,CABYR,SLC3A1,SE...",5,"0.0,42.0,19.0,39.0,20.0,17.0,14.0,33.0,21.0,37...","0.0020445194,0.0031070835,0.0025515305,0.00327...","0.0040934836,0.0028073455,0.0034256505,0.00244...","0.0043800664,0.0029222732,0.0025062195,0.00437...","0.0034533436,0.0025593678,0.003978598,0.002954...","0.0038189043,0.0032943436,0.002777985,0.003936...","0.0036355853,0.0033676857,0.00409,0.0038118216...","0.0043353783,0.0040053073,0.002787665,0.002944...",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,..."
4,"<cls>,TMBIM1,SNAI1,LMCD1,ZNF347,KCNJ2,NID1,UPK...",2,"0.0,5.0,23.0,42.0,26.0,39.0,28.0,28.0,28.0,16....","0.0021203735,0.002208613,0.0047930344,0.004826...","0.0040604477,0.0039716368,0.00493733,0.0033131...","0.005657586,0.003112157,0.0040237918,0.0037283...","0.003414135,0.0037594072,0.004144798,0.0034618...","0.003272853,0.0038072,0.0030302322,0.004112403...","0.0044797715,0.004235163,0.0032671287,0.003604...","0.0043147453,0.0030068154,0.002950847,0.006144...",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,..."

In [7]:
cells_features.shape

(499, 16326)

In [8]:
# Get column names
column_names = cells_features.columns[103:].tolist()
print(f"Number of columns: {len(column_names)}")

# Print column names line by line
print("Column names:")
for col in column_names:
    print(col)

# Create a DataFrame with column names
feature_df = pd.DataFrame(column_names, columns=['feature'])

# Save the column names as a CSV file
output_path = os.path.join(data_dir, 'feature_list.csv')
feature_df.to_csv(output_path, index=False)

print(f"\nFeature list saved to: {output_path}")

Number of columns: 16223
Column names:
HALLMARK_ADIPOGENESIS
HALLMARK_ALLOGRAFT_REJECTION
HALLMARK_ANDROGEN_RESPONSE
HALLMARK_ANGIOGENESIS
HALLMARK_APICAL_JUNCTION
HALLMARK_APICAL_SURFACE
HALLMARK_APOPTOSIS
HALLMARK_BILE_ACID_METABOLISM
HALLMARK_CHOLESTEROL_HOMEOSTASIS
HALLMARK_COAGULATION
HALLMARK_COMPLEMENT
HALLMARK_DNA_REPAIR
HALLMARK_E2F_TARGETS
HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION
HALLMARK_ESTROGEN_RESPONSE_EARLY
HALLMARK_ESTROGEN_RESPONSE_LATE
HALLMARK_FATTY_ACID_METABOLISM
HALLMARK_G2M_CHECKPOINT
HALLMARK_GLYCOLYSIS
HALLMARK_HEDGEHOG_SIGNALING
HALLMARK_HEME_METABOLISM
HALLMARK_HYPOXIA
HALLMARK_IL2_STAT5_SIGNALING
HALLMARK_IL6_JAK_STAT3_SIGNALING
HALLMARK_INFLAMMATORY_RESPONSE
HALLMARK_INTERFERON_ALPHA_RESPONSE
HALLMARK_INTERFERON_GAMMA_RESPONSE
HALLMARK_KRAS_SIGNALING_DN
HALLMARK_KRAS_SIGNALING_UP
HALLMARK_MITOTIC_SPINDLE
HALLMARK_MTORC1_SIGNALING
HALLMARK_MYC_TARGETS_V1
HALLMARK_MYC_TARGETS_V2
HALLMARK_MYOGENESIS
HALLMARK_NOTCH_SIGNALING
HALLMARK_OXIDATIVE_PHOSPHORYLATION
HALLMARK_P53_PATHWAY
HALLMARK_PANCREAS_BETA_CELLS
HALLMARK_PEROXISOME
HALLMARK_PI3K_AKT_MTOR_SIGNALING
HALLMARK_PROTEIN_SECRETION
HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY
HALLMARK_SPERMATOGENESIS
HALLMARK_TGF_BETA_SIGNALING
HALLMARK_TNFA_SIGNALING_VIA_NFKB
HALLMARK_UNFOLDED_PROTEIN_RESPONSE
HALLMARK_UV_RESPONSE_DN
HALLMARK_UV_RESPONSE_UP
HALLMARK_WNT_BETA_CATENIN_SIGNALING
HALLMARK_XENOBIOTIC_METABOLISM
AIZARANI_LIVER_C10_MVECS_1
AIZARANI_LIVER_C11_HEPATOCYTES_1
AIZARANI_LIVER_C12_NK_NKT_CELLS_4
AIZARANI_LIVER_C13_LSECS_2
AIZARANI_LIVER_C14_HEPATOCYTES_2
AIZARANI_LIVER_C17_HEPATOCYTES_3
AIZARANI_LIVER_C18_NK_NKT_CELLS_5
AIZARANI_LIVER_C1_NK_NKT_CELLS_1
AIZARANI_LIVER_C20_LSECS_3
AIZARANI_LIVER_C21_STELLATE_CELLS_1
AIZARANI_LIVER_C22_RESIDENT_B_CELLS_2
AIZARANI_LIVER_C23_KUPFFER_CELLS_3
AIZARANI_LIVER_C24_EPCAM_POS_BILE_DUCT_CELLS_3
AIZARANI_LIVER_C25_KUPFFER_CELLS_4
AIZARANI_LIVER_C28_NK_NKT_CELLS_6
AIZARANI_LIVER_C29_MVECS_2
AIZARANI_LIVER_C2_KUPFFER_CELLS_1
AIZARANI_LIVER_C30_HEPATOCYTES_4
AIZARANI_LIVER_C31_KUPFFER_CELLS_5
AIZARANI_LIVER_C32_MVECS_3
AIZARANI_LIVER_C33_STELLATE_CELLS_2
AIZARANI_LIVER_C34_MHC_II_POS_B_CELLS
AIZARANI_LIVER_C38_RESIDENT_B_CELLS_3
AIZARANI_LIVER_C39_EPCAM_POS_BILE_DUCT_CELLS_4
AIZARANI_LIVER_C3_NK_NKT_CELLS_2
AIZARANI_LIVER_C4_EPCAM_POS_BILE_DUCT_CELLS_1
AIZARANI_LIVER_C5_NK_NKT_CELLS_3
AIZARANI_LIVER_C6_KUPFFER_CELLS_2
AIZARANI_LIVER_C7_EPCAM_POS_BILE_DUCT_CELLS_2
AIZARANI_LIVER_C8_RESIDENT_B_CELLS_1
AIZARANI_LIVER_C9_LSECS_1
BUSSLINGER_DUODENAL_BCHE_CELLS
BUSSLINGER_DUODENAL_DIFFERENTIATING_STEM_CELLS
BUSSLINGER_DUODENAL_EARLY_IMMATURE_ENTEROCYTES
BUSSLINGER_DUODENAL_EC_CELLS
BUSSLINGER_DUODENAL_GOBLET_CELLS
BUSSLINGER_DUODENAL_IMMUNE_CELLS
BUSSLINGER_DUODENAL_I_CELLS
BUSSLINGER_DUODENAL_K_CELLS
BUSSLINGER_DUODENAL_LATE_IMMATURE_ENTEROCYTES
BUSSLINGER_DUODENAL_MATURE_ENTEROCYTES
BUSSLINGER_DUODENAL_MX_CELLS
BUSSLINGER_DUODENAL_PANETH_CELLS
BUSSLINGER_DUODENAL_STEM_CELLS
BUSSLINGER_DUODENAL_TRANSIT_AMPLIFYING_CELLS
BUSSLINGER_DUODENAL_TUFT_CELLS
BUSSLINGER_ESOPHAGEAL_DENDRITIC_CELLS
BUSSLINGER_ESOPHAGEAL_EARLY_SUPRABASAL_CELLS
BUSSLINGER_ESOPHAGEAL_LATE_SUPRABASAL_CELLS
BUSSLINGER_ESOPHAGEAL_PROLIFERATING_BASAL_CELLS
BUSSLINGER_ESOPHAGEAL_QUIESCENT_BASAL_CELLS
BUSSLINGER_GASTRIC_ANTRAL_ECS
BUSSLINGER_GASTRIC_CHIEF_CELLS
BUSSLINGER_GASTRIC_D_CELLS
BUSSLINGER_GASTRIC_G_CELLS
BUSSLINGER_GASTRIC_IMMATURE_PIT_CELLS
BUSSLINGER_GASTRIC_IMMUNE_CELLS
BUSSLINGER_GASTRIC_ISTHMUS_CELLS
BUSSLINGER_GASTRIC_LYZ_POSITIVE_CELLS
BUSSLINGER_GASTRIC_MATURE_PIT_CELLS
BUSSLINGER_GASTRIC_METALLOTHIONEIN_CELLS
BUSSLINGER_GASTRIC_NECK_CELLS
BUSSLINGER_GASTRIC_OXYNTIC_ENTEROCHROMAFFIN_LIKE_CELLS
BUSSLINGER_GASTRIC_PARIETAL_CELLS
BUSSLINGER_GASTRIC_PPP1R1B_POSITIVE_CELLS
BUSSLINGER_GASTRIC_PREZYMOGENIC_CELLS
BUSSLINGER_GASTRIC_REG3A_POSITIVE_CELLS
BUSSLINGER_GASTRIC_TUFT_CELLS
BUSSLINGER_GASTRIC_X_CELLS
CUI_DEVELOPING_HEART_5TH_WEEK_ATRIAL_CARDIOMYOCYTE
CUI_DEVELOPING_HEART_5TH_WEEK_VENTRICULAR_CARDIOMYOCYTE
CUI_DEVELOPING_HEART_C1_5TH_WEEK_CARDIAC_CELLS
CUI_DEVELOPING_HEART_C2_CARDIOMYOCYTE
CUI_DEVELOPING_HEART_C3_FIBROBLAST_LIKE_CELL
CUI_DEVELOPING_HEART_C4_ENDOTHELIAL_CELL
CUI_DEVELOPING_HEART_C5_VALVAR_CELL
CUI_DEVELOPING_HEART_C6_EPICARDIAL_CELL
CUI_DEVELOPING_HEART_C7_MAST_CELL
CUI_DEVELOPING_HEART_C8_MACROPHAGE
CUI_DEVELOPING_HEART_C9_B_T_CELL
CUI_DEVELOPING_HEART_CARDIAC_FIBROBLASTS
CUI_DEVELOPING_HEART_COMPACT_ATRIAL_CARDIOMYOCYTE
CUI_DEVELOPING_HEART_COMPACT_VENTRICULAR_CARDIOMYOCYTE
CUI_DEVELOPING_HEART_CORONARY_VASCULAR_ENDOTHELIAL_CELL
CUI_DEVELOPING_HEART_ENDOCARDIAL_CELL
CUI_DEVELOPING_HEART_LEFT_ATRIAL_CARDIOMYOCYTE
CUI_DEVELOPING_HEART_LEFT_VENTRICULAR_CARDIOMYOCYTE
CUI_DEVELOPING_HEART_RIGHT_ATRIAL_CARDIOMYOCYTE
CUI_DEVELOPING_HEART_RIGHT_VENTRICULAR_CARDIOMYOCYTE
CUI_DEVELOPING_HEART_SMOOTH_MUSCLE_CELL
CUI_DEVELOPING_HEART_TRABECULAR_ATRIAL_CARDIOMYOCYTE
CUI_DEVELOPING_HEART_TRABECULAR_VENTRICULAR_CARDIOMYOCYTE
CUI_DEVELOPING_HEART_VALVAR_ENDOTHELIAL_CELL
CUI_DEVELOPING_HEART_VASCULAR_ENDOTHELIAL_CELL
DESCARTES_FETAL_ADRENAL_ADRENOCORTICAL_CELLS
DESCARTES_FETAL_ADRENAL_CHROMAFFIN_CELLS
DESCARTES_FETAL_ADRENAL_CSH1_CSH2_POSITIVE_CELLS
DESCARTES_FETAL_ADRENAL_ERYTHROBLASTS
DESCARTES_FETAL_ADRENAL_LYMPHOID_CELLS
DESCARTES_FETAL_ADRENAL_MEGAKARYOCYTES
DESCARTES_FETAL_ADRENAL_MYELOID_CELLS
DESCARTES_FETAL_ADRENAL_SCHWANN_CELLS
DESCARTES_FETAL_ADRENAL_SLC26A4_PAEP_POSITIVE_CELLS
DESCARTES_FETAL_ADRENAL_STROMAL_CELLS
DESCARTES_FETAL_ADRENAL_SYMPATHOBLASTS
DESCARTES_FETAL_ADRENAL_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_FETAL_CEREBELLUM_ASTROCYTES
DESCARTES_FETAL_CEREBELLUM_GRANULE_NEURONS
DESCARTES_FETAL_CEREBELLUM_INHIBITORY_INTERNEURONS
DESCARTES_FETAL_CEREBELLUM_MICROGLIA
DESCARTES_FETAL_CEREBELLUM_OLIGODENDROCYTES
DESCARTES_FETAL_CEREBELLUM_PURKINJE_NEURONS
DESCARTES_FETAL_CEREBELLUM_SLC24A4_PEX5L_POSITIVE_CELLS
DESCARTES_FETAL_CEREBELLUM_UNIPOLAR_BRUSH_CELLS
DESCARTES_FETAL_CEREBELLUM_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_FETAL_CEREBRUM_ASTROCYTES
DESCARTES_FETAL_CEREBRUM_EXCITATORY_NEURONS
DESCARTES_FETAL_CEREBRUM_INHIBITORY_NEURONS
DESCARTES_FETAL_CEREBRUM_LIMBIC_SYSTEM_NEURONS
DESCARTES_FETAL_CEREBRUM_MEGAKARYOCYTES
DESCARTES_FETAL_CEREBRUM_MICROGLIA
DESCARTES_FETAL_CEREBRUM_OLIGODENDROCYTES
DESCARTES_FETAL_CEREBRUM_SKOR2_NPSR1_POSITIVE_CELLS
DESCARTES_FETAL_CEREBRUM_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_FETAL_EYE_AMACRINE_CELLS
DESCARTES_FETAL_EYE_ASTROCYTES
DESCARTES_FETAL_EYE_BIPOLAR_CELLS
DESCARTES_FETAL_EYE_CORNEAL_AND_CONJUNCTIVAL_EPITHELIAL_CELLS
DESCARTES_FETAL_EYE_GANGLION_CELLS
DESCARTES_FETAL_EYE_HORIZONTAL_CELLS
DESCARTES_FETAL_EYE_LENS_FIBRE_CELLS
DESCARTES_FETAL_EYE_MICROGLIA
DESCARTES_FETAL_EYE_PDE11A_FAM19A2_POSITIVE_CELLS
DESCARTES_FETAL_EYE_PHOTORECEPTOR_CELLS
DESCARTES_FETAL_EYE_RETINAL_PIGMENT_CELLS
DESCARTES_FETAL_EYE_RETINAL_PROGENITORS_AND_MULLER_GLIA
DESCARTES_FETAL_EYE_SKELETAL_MUSCLE_CELLS
DESCARTES_FETAL_EYE_SMOOTH_MUSCLE_CELLS
DESCARTES_FETAL_EYE_STROMAL_CELLS
DESCARTES_FETAL_EYE_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_FETAL_HEART_CARDIOMYOCYTES
DESCARTES_FETAL_HEART_CLC_IL5RA_POSITIVE_CELLS
DESCARTES_FETAL_HEART_ELF3_AGBL2_POSITIVE_CELLS
DESCARTES_FETAL_HEART_ENDOCARDIAL_CELLS
DESCARTES_FETAL_HEART_EPICARDIAL_FAT_CELLS
DESCARTES_FETAL_HEART_ERYTHROBLASTS
DESCARTES_FETAL_HEART_LYMPHATIC_ENDOTHELIAL_CELLS
DESCARTES_FETAL_HEART_LYMPHOID_CELLS
DESCARTES_FETAL_HEART_MEGAKARYOCYTES
DESCARTES_FETAL_HEART_MYELOID_CELLS
DESCARTES_FETAL_HEART_SATB2_LRRC7_POSITIVE_CELLS
DESCARTES_FETAL_HEART_SCHWANN_CELLS
DESCARTES_FETAL_HEART_SMOOTH_MUSCLE_CELLS
DESCARTES_FETAL_HEART_STROMAL_CELLS
DESCARTES_FETAL_HEART_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_FETAL_HEART_VISCERAL_NEURONS
DESCARTES_FETAL_INTESTINE_CHROMAFFIN_CELLS
DESCARTES_FETAL_INTESTINE_ENS_GLIA
DESCARTES_FETAL_INTESTINE_ENS_NEURONS
DESCARTES_FETAL_INTESTINE_ERYTHROBLASTS
DESCARTES_FETAL_INTESTINE_INTESTINAL_EPITHELIAL_CELLS
DESCARTES_FETAL_INTESTINE_LYMPHATIC_ENDOTHELIAL_CELLS
DESCARTES_FETAL_INTESTINE_LYMPHOID_CELLS
DESCARTES_FETAL_INTESTINE_MESOTHELIAL_CELLS
DESCARTES_FETAL_INTESTINE_MYELOID_CELLS
DESCARTES_FETAL_INTESTINE_SMOOTH_MUSCLE_CELLS
DESCARTES_FETAL_INTESTINE_STROMAL_CELLS
DESCARTES_FETAL_INTESTINE_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_FETAL_KIDNEY_ERYTHROBLASTS
DESCARTES_FETAL_KIDNEY_LYMPHOID_CELLS
DESCARTES_FETAL_KIDNEY_MEGAKARYOCYTES
DESCARTES_FETAL_KIDNEY_MESANGIAL_CELLS
DESCARTES_FETAL_KIDNEY_METANEPHRIC_CELLS
DESCARTES_FETAL_KIDNEY_MYELOID_CELLS
DESCARTES_FETAL_KIDNEY_STROMAL_CELLS
DESCARTES_FETAL_KIDNEY_URETERIC_BUD_CELLS
DESCARTES_FETAL_KIDNEY_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_FETAL_LIVER_ERYTHROBLASTS
DESCARTES_FETAL_LIVER_HEMATOPOIETIC_STEM_CELLS
DESCARTES_FETAL_LIVER_HEPATOBLASTS
DESCARTES_FETAL_LIVER_LYMPHOID_CELLS
DESCARTES_FETAL_LIVER_MEGAKARYOCYTES
DESCARTES_FETAL_LIVER_MESOTHELIAL_CELLS
DESCARTES_FETAL_LIVER_MYELOID_CELLS
DESCARTES_FETAL_LIVER_STELLATE_CELLS
DESCARTES_FETAL_LIVER_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_FETAL_LUNG_BRONCHIOLAR_AND_ALVEOLAR_EPITHELIAL_CELLS
DESCARTES_FETAL_LUNG_CILIATED_EPITHELIAL_CELLS
DESCARTES_FETAL_LUNG_CSH1_CSH2_POSITIVE_CELLS
DESCARTES_FETAL_LUNG_LYMPHATIC_ENDOTHELIAL_CELLS
DESCARTES_FETAL_LUNG_LYMPHOID_CELLS
DESCARTES_FETAL_LUNG_MEGAKARYOCYTES
DESCARTES_FETAL_LUNG_MESOTHELIAL_CELLS
DESCARTES_FETAL_LUNG_MYELOID_CELLS
DESCARTES_FETAL_LUNG_NEUROENDOCRINE_CELLS
DESCARTES_FETAL_LUNG_SQUAMOUS_EPITHELIAL_CELLS
DESCARTES_FETAL_LUNG_STROMAL_CELLS
DESCARTES_FETAL_LUNG_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_FETAL_LUNG_VISCERAL_NEURONS
DESCARTES_FETAL_MUSCLE_ERYTHROBLASTS
DESCARTES_FETAL_MUSCLE_LYMPHATIC_ENDOTHELIAL_CELLS
DESCARTES_FETAL_MUSCLE_LYMPHOID_CELLS
DESCARTES_FETAL_MUSCLE_MEGAKARYOCYTES
DESCARTES_FETAL_MUSCLE_MYELOID_CELLS
DESCARTES_FETAL_MUSCLE_SATELLITE_CELLS
DESCARTES_FETAL_MUSCLE_SCHWANN_CELLS
DESCARTES_FETAL_MUSCLE_SKELETAL_MUSCLE_CELLS
DESCARTES_FETAL_MUSCLE_SMOOTH_MUSCLE_CELLS
DESCARTES_FETAL_MUSCLE_STROMAL_CELLS
DESCARTES_FETAL_MUSCLE_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_FETAL_PANCREAS_ACINAR_CELLS
DESCARTES_FETAL_PANCREAS_CCL19_CCL21_POSITIVE_CELLS
DESCARTES_FETAL_PANCREAS_DUCTAL_CELLS
DESCARTES_FETAL_PANCREAS_ENS_GLIA
DESCARTES_FETAL_PANCREAS_ENS_NEURONS
DESCARTES_FETAL_PANCREAS_ERYTHROBLASTS
DESCARTES_FETAL_PANCREAS_ISLET_ENDOCRINE_CELLS
DESCARTES_FETAL_PANCREAS_LYMPHATIC_ENDOTHELIAL_CELLS
DESCARTES_FETAL_PANCREAS_LYMPHOID_CELLS
DESCARTES_FETAL_PANCREAS_MESOTHELIAL_CELLS
DESCARTES_FETAL_PANCREAS_MYELOID_CELLS
DESCARTES_FETAL_PANCREAS_SMOOTH_MUSCLE_CELLS
DESCARTES_FETAL_PANCREAS_STROMAL_CELLS
DESCARTES_FETAL_PANCREAS_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_FETAL_PLACENTA_AFP_ALB_POSITIVE_CELLS
DESCARTES_FETAL_PLACENTA_EXTRAVILLOUS_TROPHOBLASTS
DESCARTES_FETAL_PLACENTA_IGFBP1_DKK1_POSITIVE_CELLS
DESCARTES_FETAL_PLACENTA_LYMPHOID_CELLS
DESCARTES_FETAL_PLACENTA_MEGAKARYOCYTES
DESCARTES_FETAL_PLACENTA_MYELOID_CELLS
DESCARTES_FETAL_PLACENTA_PAEP_MECOM_POSITIVE_CELLS
DESCARTES_FETAL_PLACENTA_SMOOTH_MUSCLE_CELLS
DESCARTES_FETAL_PLACENTA_STROMAL_CELLS
DESCARTES_FETAL_PLACENTA_SYNCYTIOTROPHOBLASTS_AND_VILLOUS_CYTOTROPHOBLASTS
DESCARTES_FETAL_PLACENTA_TROPHOBLAST_GIANT_CELLS
DESCARTES_FETAL_PLACENTA_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_FETAL_SPLEEN_AFP_ALB_POSITIVE_CELLS
DESCARTES_FETAL_SPLEEN_ERYTHROBLASTS
DESCARTES_FETAL_SPLEEN_LYMPHOID_CELLS
DESCARTES_FETAL_SPLEEN_MEGAKARYOCYTES
DESCARTES_FETAL_SPLEEN_MESOTHELIAL_CELLS
DESCARTES_FETAL_SPLEEN_MYELOID_CELLS
DESCARTES_FETAL_SPLEEN_STC2_TLX1_POSITIVE_CELLS
DESCARTES_FETAL_SPLEEN_STROMAL_CELLS
DESCARTES_FETAL_SPLEEN_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_FETAL_STOMACH_CILIATED_EPITHELIAL_CELLS
DESCARTES_FETAL_STOMACH_ENS_GLIA
DESCARTES_FETAL_STOMACH_ENS_NEURONS
DESCARTES_FETAL_STOMACH_ERYTHROBLASTS
DESCARTES_FETAL_STOMACH_GOBLET_CELLS
DESCARTES_FETAL_STOMACH_LYMPHATIC_ENDOTHELIAL_CELLS
DESCARTES_FETAL_STOMACH_LYMPHOID_CELLS
DESCARTES_FETAL_STOMACH_MESOTHELIAL_CELLS
DESCARTES_FETAL_STOMACH_MUC13_DMBT1_POSITIVE_CELLS
DESCARTES_FETAL_STOMACH_MYELOID_CELLS
DESCARTES_FETAL_STOMACH_NEUROENDOCRINE_CELLS
DESCARTES_FETAL_STOMACH_PARIETAL_AND_CHIEF_CELLS
DESCARTES_FETAL_STOMACH_PDE1C_ACSM3_POSITIVE_CELLS
DESCARTES_FETAL_STOMACH_SQUAMOUS_EPITHELIAL_CELLS
DESCARTES_FETAL_STOMACH_STROMAL_CELLS
DESCARTES_FETAL_STOMACH_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_FETAL_THYMUS_ANTIGEN_PRESENTING_CELLS
DESCARTES_FETAL_THYMUS_STROMAL_CELLS
DESCARTES_FETAL_THYMUS_THYMIC_EPITHELIAL_CELLS
DESCARTES_FETAL_THYMUS_THYMOCYTES
DESCARTES_FETAL_THYMUS_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_MAIN_FETAL_ACINAR_CELLS
DESCARTES_MAIN_FETAL_ADRENOCORTICAL_CELLS
DESCARTES_MAIN_FETAL_AFP_ALB_POSITIVE_CELLS
DESCARTES_MAIN_FETAL_AMACRINE_CELLS
DESCARTES_MAIN_FETAL_ANTIGEN_PRESENTING_CELLS
DESCARTES_MAIN_FETAL_ASTROCYTES
DESCARTES_MAIN_FETAL_BIPOLAR_CELLS
DESCARTES_MAIN_FETAL_BRONCHIOLAR_AND_ALVEOLAR_EPITHELIAL_CELLS
DESCARTES_MAIN_FETAL_CARDIOMYOCYTES
DESCARTES_MAIN_FETAL_CCL19_CCL21_POSITIVE_CELLS
DESCARTES_MAIN_FETAL_CHROMAFFIN_CELLS
DESCARTES_MAIN_FETAL_CILIATED_EPITHELIAL_CELLS
DESCARTES_MAIN_FETAL_CLC_IL5RA_POSITIVE_CELLS
DESCARTES_MAIN_FETAL_CORNEAL_AND_CONJUNCTIVAL_EPITHELIAL_CELLS
DESCARTES_MAIN_FETAL_CSH1_CSH2_POSITIVE_CELLS
DESCARTES_MAIN_FETAL_DUCTAL_CELLS
DESCARTES_MAIN_FETAL_ELF3_AGBL2_POSITIVE_CELLS
DESCARTES_MAIN_FETAL_ENDOCARDIAL_CELLS
DESCARTES_MAIN_FETAL_ENS_GLIA
DESCARTES_MAIN_FETAL_ENS_NEURONS
DESCARTES_MAIN_FETAL_EPICARDIAL_FAT_CELLS
DESCARTES_MAIN_FETAL_ERYTHROBLASTS
DESCARTES_MAIN_FETAL_EXCITATORY_NEURONS
DESCARTES_MAIN_FETAL_EXTRAVILLOUS_TROPHOBLASTS
DESCARTES_MAIN_FETAL_GANGLION_CELLS
DESCARTES_MAIN_FETAL_GOBLET_CELLS
DESCARTES_MAIN_FETAL_GRANULE_NEURONS
DESCARTES_MAIN_FETAL_HEMATOPOIETIC_STEM_CELLS
DESCARTES_MAIN_FETAL_HEPATOBLASTS
DESCARTES_MAIN_FETAL_HORIZONTAL_CELLS
DESCARTES_MAIN_FETAL_IGFBP1_DKK1_POSITIVE_CELLS
DESCARTES_MAIN_FETAL_INHIBITORY_INTERNEURONS
DESCARTES_MAIN_FETAL_INHIBITORY_NEURONS
DESCARTES_MAIN_FETAL_INTESTINAL_EPITHELIAL_CELLS
DESCARTES_MAIN_FETAL_ISLET_ENDOCRINE_CELLS
DESCARTES_MAIN_FETAL_LENS_FIBRE_CELLS
DESCARTES_MAIN_FETAL_LIMBIC_SYSTEM_NEURONS
DESCARTES_MAIN_FETAL_LYMPHATIC_ENDOTHELIAL_CELLS
DESCARTES_MAIN_FETAL_LYMPHOID_CELLS
DESCARTES_MAIN_FETAL_MEGAKARYOCYTES
DESCARTES_MAIN_FETAL_MESANGIAL_CELLS
DESCARTES_MAIN_FETAL_MESOTHELIAL_CELLS
DESCARTES_MAIN_FETAL_METANEPHRIC_CELLS
DESCARTES_MAIN_FETAL_MICROGLIA
DESCARTES_MAIN_FETAL_MUC13_DMBT1_POSITIVE_CELLS
DESCARTES_MAIN_FETAL_MYELOID_CELLS
DESCARTES_MAIN_FETAL_NEUROENDOCRINE_CELLS
DESCARTES_MAIN_FETAL_OLIGODENDROCYTES
DESCARTES_MAIN_FETAL_PAEP_MECOM_POSITIVE_CELLS
DESCARTES_MAIN_FETAL_PARIETAL_AND_CHIEF_CELLS
DESCARTES_MAIN_FETAL_PDE11A_FAM19A2_POSITIVE_CELLS
DESCARTES_MAIN_FETAL_PDE1C_ACSM3_POSITIVE_CELLS
DESCARTES_MAIN_FETAL_PHOTORECEPTOR_CELLS
DESCARTES_MAIN_FETAL_RETINAL_PIGMENT_CELLS
DESCARTES_MAIN_FETAL_RETINAL_PROGENITORS_AND_MULLER_GLIA
DESCARTES_MAIN_FETAL_SATB2_LRRC7_POSITIVE_CELLS
DESCARTES_MAIN_FETAL_SATELLITE_CELLS
DESCARTES_MAIN_FETAL_SCHWANN_CELLS
DESCARTES_MAIN_FETAL_SKELETAL_MUSCLE_CELLS
DESCARTES_MAIN_FETAL_SLC24A4_PEX5L_POSITIVE_CELLS
DESCARTES_MAIN_FETAL_SLC26A4_PAEP_POSITIVE_CELLS
DESCARTES_MAIN_FETAL_SMOOTH_MUSCLE_CELLS
DESCARTES_MAIN_FETAL_SQUAMOUS_EPITHELIAL_CELLS
DESCARTES_MAIN_FETAL_STC2_TLX1_POSITIVE_CELLS
DESCARTES_MAIN_FETAL_STELLATE_CELLS
DESCARTES_MAIN_FETAL_STROMAL_CELLS
DESCARTES_MAIN_FETAL_SYMPATHOBLASTS
DESCARTES_MAIN_FETAL_SYNCYTIOTROPHOBLASTS_AND_VILLOUS_CYTOTROPHOBLASTS
DESCARTES_MAIN_FETAL_THYMIC_EPITHELIAL_CELLS
DESCARTES_MAIN_FETAL_THYMOCYTES
DESCARTES_MAIN_FETAL_TROPHOBLAST_GIANT_CELLS
DESCARTES_MAIN_FETAL_UNIPOLAR_BRUSH_CELLS
DESCARTES_MAIN_FETAL_URETERIC_BUD_CELLS
DESCARTES_MAIN_FETAL_VASCULAR_ENDOTHELIAL_CELLS
DESCARTES_MAIN_FETAL_VISCERAL_NEURONS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_BOWMANS_GLAND
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_B_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_CD4_T_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_CD8_T_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_DENDRITIC_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_FIBROBLASTS_STROMAL_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_GLOBOSE_BASAL_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_IMMATURE_NEURONS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_MACROPHAGES
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_MAST_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_MATURE_NEURONS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_MONOCYTES
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_NK_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_OLFACTORY_ENSHEATHING_GLIA
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_OLFACTORY_HORIZONTAL_BASAL_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_OLFACTORY_MICROVILLAR_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_PERICYTES
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_PLASMA_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_RESPIRATORY_CILIATED_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_RESPIRATORY_COLUMNAR_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_RESPIRATORY_EPITHELIAL_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_RESPIRATORY_HORIZONTAL_BASAL_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_RESPIRATORY_SECRETORY_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_SUSTENTACULAR_CELLS
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_UNSPECIFIED
DURANTE_ADULT_OLFACTORY_NEUROEPITHELIUM_VASCULAR_SMOOTH_MUSCLE_CELLS
FAN_EMBRYONIC_CTX_ASTROCYTE_1
FAN_EMBRYONIC_CTX_ASTROCYTE_2
FAN_EMBRYONIC_CTX_BIG_GROUPS_BRAIN_ENDOTHELIAL
FAN_EMBRYONIC_CTX_BIG_GROUPS_BRAIN_IMMUNE
FAN_EMBRYONIC_CTX_BIG_GROUPS_CAJAL_RETZIUS
FAN_EMBRYONIC_CTX_BIG_GROUPS_EXCITATORY_NEURON
FAN_EMBRYONIC_CTX_BIG_GROUPS_GLIAL
FAN_EMBRYONIC_CTX_BIG_GROUPS_INHIBITORY
FAN_EMBRYONIC_CTX_BIG_GROUPS_MICROGLIA
FAN_EMBRYONIC_CTX_BRAIN_B_CELL
FAN_EMBRYONIC_CTX_BRAIN_EFFECTOR_T_CELL
FAN_EMBRYONIC_CTX_BRAIN_ENDOTHELIAL_1
FAN_EMBRYONIC_CTX_BRAIN_ENDOTHELIAL_2
FAN_EMBRYONIC_CTX_BRAIN_MYELOID
FAN_EMBRYONIC_CTX_BRAIN_NAIVE_LIKE_T_CELL
FAN_EMBRYONIC_CTX_EX_1_EXCITATORY_NEURON
FAN_EMBRYONIC_CTX_EX_2_EXCITATORY_NEURON
FAN_EMBRYONIC_CTX_EX_4_EXCITATORY_NEURON
FAN_EMBRYONIC_CTX_IN_1_INTERNEURON
FAN_EMBRYONIC_CTX_IN_2_INTERNEURON
FAN_EMBRYONIC_CTX_IN_3_INTERNEURON
FAN_EMBRYONIC_CTX_IN_4_INTERNEURON
FAN_EMBRYONIC_CTX_IN_5_INTERNEURON
FAN_EMBRYONIC_CTX_IN_6_INTERNEURON
FAN_EMBRYONIC_CTX_MICROGLIA_1
FAN_EMBRYONIC_CTX_MICROGLIA_2
FAN_EMBRYONIC_CTX_MICROGLIA_3
FAN_EMBRYONIC_CTX_NSC_1
FAN_EMBRYONIC_CTX_NSC_2
FAN_EMBRYONIC_CTX_OLIG
FAN_EMBRYONIC_CTX_OPC
FAN_OVARY_CL0_XBP1_SELK_HIGH_STROMAL_CELL
FAN_OVARY_CL10_PUTATIVE_EARLY_ATRESIA_GRANULOSA_CELL
FAN_OVARY_CL11_MURAL_GRANULOSA_CELL
FAN_OVARY_CL12_T_LYMPHOCYTE_NK_CELL_2
FAN_OVARY_CL13_MONOCYTE_MACROPHAGE
FAN_OVARY_CL14_MATURE_SMOOTH_MUSCLE_CELL
FAN_OVARY_CL15_SMALL_ANTRAL_FOLLICLE_GRANULOSA_CELL
FAN_OVARY_CL16_LYMPHATIC_ENDOTHELIAL_CELL
FAN_OVARY_CL17_PUTATIVE_APOPTOTIC_SMOOTH_MUSCLE_CELL
FAN_OVARY_CL18_B_LYMPHOCYTE
FAN_OVARY_CL1_GPRC5A_TNFRS12A_HIGH_SELECTABLE_FOLLICLE_STROMAL_CELL
FAN_OVARY_CL2_PUTATIVE_EARLY_ATRETIC_FOLLICLE_THECAL_CELL_1
FAN_OVARY_CL3_MATURE_CUMULUS_GRANULOSA_CELL_1
FAN_OVARY_CL4_T_LYMPHOCYTE_NK_CELL_1
FAN_OVARY_CL5_HEALTHY_SELECTABLE_FOLLICLE_THECAL_CELL
FAN_OVARY_CL6_PUTATIVE_EARLY_ATRETIC_FOLLICLE_THECAL_CELL_2
FAN_OVARY_CL7_ANGEIOGENIC_ENDOTHELIAL_CELL
FAN_OVARY_CL8_MATURE_CUMULUS_GRANULOSA_CELL_2
FAN_OVARY_CL9_PUTATIVE_APOPTOTIC_ENDOTHELIAL_CELL
GAO_ESOPHAGUS_25W_C1_CILIATED_EPITHELIAL_CELLS
GAO_ESOPHAGUS_25W_C2_KRT6BPOS_SECRETORY_PROGENITOR_CELLS
GAO_ESOPHAGUS_25W_C3_FGFR1LOW_EPITHELIAL_CELLS
GAO_ESOPHAGUS_25W_C4_FGFR1HIGH_EPITHELIAL_CELLS
GAO_LARGE_INTESTINE_24W_C10_ENTEROCYTE
GAO_LARGE_INTESTINE_24W_C11_PANETH_LIKE_CELL
GAO_LARGE_INTESTINE_24W_C1_DCLK1POS_PROGENITOR
GAO_LARGE_INTESTINE_24W_C2_MKI67POS_PROGENITOR
GAO_LARGE_INTESTINE_24W_C4_PROM1LOW_PROGENITOR
GAO_LARGE_INTESTINE_24W_C5_LGR5POS_STEM_CELL
GAO_LARGE_INTESTINE_24W_C6_SECRETORY_PROGENITOR
GAO_LARGE_INTESTINE_24W_C7_GOBLET_PROGENITOR
GAO_LARGE_INTESTINE_24W_C8_GOBLET_CELL
GAO_LARGE_INTESTINE_ADULT_CA_ENTEROENDOCRINE_CELLS
GAO_LARGE_INTESTINE_ADULT_CE_OLFM4HIGH_STEM_CELL
GAO_LARGE_INTESTINE_ADULT_CF_GOBLET_CELL_SUBTYPE_1
GAO_LARGE_INTESTINE_ADULT_CG_GOBLET_CELL_SUBTYPE_2
GAO_LARGE_INTESTINE_ADULT_CH_MKI67HIGH_CELLS
GAO_LARGE_INTESTINE_ADULT_CI_MESENCHYMAL_CELLS
GAO_LARGE_INTESTINE_ADULT_CJ_IMMUNE_CELLS

In [9]:
features_ms = [
    "BUSSLINGER_GASTRIC_IMMUNE_CELLS",
    "FAN_OVARY_CL8_MATURE_CUMULUS_GRANULOSA_CELL_2",
    "MANNO_MIDBRAIN_NEUROTYPES_HENDO",
    "MANNO_MIDBRAIN_NEUROTYPES_HGABA",
    "MANNO_MIDBRAIN_NEUROTYPES_HPERIC",
    "MURARO_PANCREAS_DUCTAL_CELL",
    "TRAVAGLINI_LUNG_PROLIFERATING_MACROPHAGE_CELL",
    "TRAVAGLINI_LUNG_PROXIMAL_CILIATED_CELL",
    "GOBP_ANATOMICAL_STRUCTURE_FORMATION_INVOLVED_IN_MORPHOGENESIS",
    "GOBP_BIOLOGICAL_ADHESION",
    "GOBP_CATION_TRANSPORT",
    "GOBP_CELLULAR_MACROMOLECULE_LOCALIZATION",
    "GOBP_CELLULAR_RESPONSE_TO_ENDOGENOUS_STIMULUS",
    "GOBP_CELLULAR_RESPONSE_TO_STRESS",
    "GOBP_CELL_CELL_SIGNALING",
    "GOBP_CELL_MIGRATION",
    "GOBP_CELL_PROJECTION_ORGANIZATION",
    "GOBP_CENTRAL_NERVOUS_SYSTEM_DEVELOPMENT",
    "GOBP_CHEMICAL_HOMEOSTASIS",
    "GOBP_CIRCULATORY_SYSTEM_DEVELOPMENT",
    "GOBP_CYTOSKELETON_ORGANIZATION",
    "GOBP_ESTABLISHMENT_OF_PROTEIN_LOCALIZATION",
    "GOBP_HOMEOSTATIC_PROCESS",
    "GOBP_INTRACELLULAR_TRANSPORT",
    "GOBP_ION_TRANSMEMBRANE_TRANSPORT",
    "GOBP_ION_TRANSPORT",
    "GOBP_LOCOMOTION",
    "GOBP_NEGATIVE_REGULATION_OF_RESPONSE_TO_STIMULUS",
    "GOBP_NEGATIVE_REGULATION_OF_SIGNALING",
    "GOBP_NERVOUS_SYSTEM_PROCESS",
    "GOBP_NEUROGENESIS",
    "GOBP_NEURON_DEVELOPMENT",
    "GOBP_NEURON_DIFFERENTIATION",
    "GOBP_NITROGEN_COMPOUND_TRANSPORT",
    "GOBP_ORGANONITROGEN_COMPOUND_BIOSYNTHETIC_PROCESS",
    "GOBP_PHOSPHORYLATION",
    "GOBP_POSITIVE_REGULATION_OF_CELLULAR_BIOSYNTHETIC_PROCESS",
    "GOBP_POSITIVE_REGULATION_OF_DEVELOPMENTAL_PROCESS",
    "GOBP_POSITIVE_REGULATION_OF_MOLECULAR_FUNCTION",
    "GOBP_POSITIVE_REGULATION_OF_MULTICELLULAR_ORGANISMAL_PROCESS",
    "GOBP_POSITIVE_REGULATION_OF_NUCLEOBASE_CONTAINING_COMPOUND_METABOLIC_PROCESS",
    "GOBP_POSITIVE_REGULATION_OF_PROTEIN_METABOLIC_PROCESS",
    "GOBP_POSITIVE_REGULATION_OF_RNA_METABOLIC_PROCESS",
    "GOBP_POSITIVE_REGULATION_OF_SIGNALING",
    "GOBP_PROGRAMMED_CELL_DEATH",
    "GOBP_PROTEIN_CONTAINING_COMPLEX_ORGANIZATION",
    "GOBP_PROTEOLYSIS",
    "GOBP_REGULATION_OF_CELL_DEATH",
    "GOBP_REGULATION_OF_CELL_DIFFERENTIATION",
    "GOBP_REGULATION_OF_CELL_POPULATION_PROLIFERATION",
    "GOBP_REGULATION_OF_INTRACELLULAR_SIGNAL_TRANSDUCTION",
    "GOBP_REGULATION_OF_MULTICELLULAR_ORGANISMAL_DEVELOPMENT",
    "GOBP_REGULATION_OF_PHOSPHORUS_METABOLIC_PROCESS",
    "GOBP_REGULATION_OF_PROTEIN_MODIFICATION_PROCESS",
    "GOBP_REGULATION_OF_TRANSPORT",
    "GOBP_REPRODUCTION",
    "GOBP_RESPONSE_TO_ABIOTIC_STIMULUS",
    "GOBP_RESPONSE_TO_ENDOGENOUS_STIMULUS",
    "GOBP_RESPONSE_TO_OXYGEN_CONTAINING_COMPOUND",
    "GOBP_SMALL_MOLECULE_METABOLIC_PROCESS",
    "GOBP_TISSUE_DEVELOPMENT",
    "GOBP_TRANSMEMBRANE_TRANSPORT",
    "GOBP_VESICLE_MEDIATED_TRANSPORT",
    "GOCC_ENDOPLASMIC_RETICULUM",
    "GOCC_ENVELOPE",
    "GOCC_GOLGI_APPARATUS",
    "GOCC_INTRINSIC_COMPONENT_OF_PLASMA_MEMBRANE",
    "GOCC_MEMBRANE_PROTEIN_COMPLEX",
    "GOCC_MITOCHONDRION",
    "GOCC_NEURON_PROJECTION",
    "GOCC_PLASMA_MEMBRANE_REGION",
    "GOCC_SECRETORY_VESICLE",
    "GOCC_SYNAPSE",
    "GOCC_VESICLE_MEMBRANE",
    "GOMF_IDENTICAL_PROTEIN_BINDING",
    "GOMF_MOLECULAR_FUNCTION_REGULATOR",
    "GOMF_PROTEIN_CONTAINING_COMPLEX_BINDING",
    "GOMF_RIBONUCLEOTIDE_BINDING",
    "GOMF_SIGNALING_RECEPTOR_BINDING",
    "GOMF_TRANSPORTER_ACTIVITY"
]

In [10]:
features_pancreas = [
    "DESCARTES_FETAL_CEREBELLUM_VASCULAR_ENDOTHELIAL_CELLS",
    "GAO_LARGE_INTESTINE_ADULT_CJ_IMMUNE_CELLS",
    "HAY_BONE_MARROW_STROMAL",
    "MANNO_MIDBRAIN_NEUROTYPES_HENDO",
    "MANNO_MIDBRAIN_NEUROTYPES_HMGL",
    "MANNO_MIDBRAIN_NEUROTYPES_HPERIC",
    "MURARO_PANCREAS_ACINAR_CELL",
    "MURARO_PANCREAS_DUCTAL_CELL",
    "MURARO_PANCREAS_MESENCHYMAL_STROMAL_CELL",
    "TRAVAGLINI_LUNG_PROLIFERATING_MACROPHAGE_CELL",
    "GOBP_ANATOMICAL_STRUCTURE_FORMATION_INVOLVED_IN_MORPHOGENESIS",
    "GOBP_ANIMAL_ORGAN_MORPHOGENESIS",
    "GOBP_BIOLOGICAL_ADHESION",
    "GOBP_BIOLOGICAL_PROCESS_INVOLVED_IN_INTERSPECIES_INTERACTION_BETWEEN_ORGANISMS",
    "GOBP_CELLULAR_RESPONSE_TO_ENDOGENOUS_STIMULUS",
    "GOBP_CELLULAR_RESPONSE_TO_OXYGEN_CONTAINING_COMPOUND",
    "GOBP_CELLULAR_RESPONSE_TO_STRESS",
    "GOBP_CELL_ACTIVATION",
    "GOBP_CELL_CELL_ADHESION",
    "GOBP_CELL_CELL_SIGNALING",
    "GOBP_CELL_CYCLE",
    "GOBP_CELL_MIGRATION",
    "GOBP_CELL_PROJECTION_ORGANIZATION",
    "GOBP_CHEMICAL_HOMEOSTASIS",
    "GOBP_CIRCULATORY_SYSTEM_DEVELOPMENT",
    "GOBP_CYTOSKELETON_ORGANIZATION",
    "GOBP_DEFENSE_RESPONSE",
    "GOBP_ENZYME_LINKED_RECEPTOR_PROTEIN_SIGNALING_PATHWAY",
    "GOBP_EPITHELIUM_DEVELOPMENT",
    "GOBP_HOMEOSTATIC_PROCESS",
    "GOBP_IMMUNE_RESPONSE",
    "GOBP_INFLAMMATORY_RESPONSE",
    "GOBP_ION_TRANSPORT",
    "GOBP_LIPID_METABOLIC_PROCESS",
    "GOBP_LOCOMOTION",
    "GOBP_NEGATIVE_REGULATION_OF_BIOSYNTHETIC_PROCESS",
    "GOBP_NEGATIVE_REGULATION_OF_CELL_DEATH",
    "GOBP_NEGATIVE_REGULATION_OF_MOLECULAR_FUNCTION",
    "GOBP_NEGATIVE_REGULATION_OF_MULTICELLULAR_ORGANISMAL_PROCESS",
    "GOBP_NEGATIVE_REGULATION_OF_RESPONSE_TO_STIMULUS",
    "GOBP_NEGATIVE_REGULATION_OF_SIGNALING",
    "GOBP_NEUROGENESIS",
    "GOBP_NEURON_DIFFERENTIATION",
    "GOBP_NITROGEN_COMPOUND_TRANSPORT",
    "GOBP_PHOSPHORYLATION",
    "GOBP_POSITIVE_REGULATION_OF_CELLULAR_BIOSYNTHETIC_PROCESS",
    "GOBP_POSITIVE_REGULATION_OF_CELL_POPULATION_PROLIFERATION",
    "GOBP_POSITIVE_REGULATION_OF_DEVELOPMENTAL_PROCESS",
    "GOBP_POSITIVE_REGULATION_OF_GENE_EXPRESSION",
    "GOBP_POSITIVE_REGULATION_OF_MOLECULAR_FUNCTION",
    "GOBP_POSITIVE_REGULATION_OF_MULTICELLULAR_ORGANISMAL_PROCESS",
    "GOBP_POSITIVE_REGULATION_OF_NUCLEOBASE_CONTAINING_COMPOUND_METABOLIC_PROCESS",
    "GOBP_POSITIVE_REGULATION_OF_PROTEIN_METABOLIC_PROCESS",
    "GOBP_POSITIVE_REGULATION_OF_RNA_METABOLIC_PROCESS",
    "GOBP_POSITIVE_REGULATION_OF_SIGNALING",
    "GOBP_PROGRAMMED_CELL_DEATH",
    "GOBP_PROTEOLYSIS",
    "GOBP_REGULATION_OF_ANATOMICAL_STRUCTURE_MORPHOGENESIS",
    "GOBP_REGULATION_OF_CELLULAR_COMPONENT_MOVEMENT",
    "GOBP_REGULATION_OF_CELL_ADHESION",
    "GOBP_REGULATION_OF_CELL_DEATH",
    "GOBP_REGULATION_OF_CELL_DIFFERENTIATION",
    "GOBP_REGULATION_OF_CELL_POPULATION_PROLIFERATION",
    "GOBP_REGULATION_OF_IMMUNE_SYSTEM_PROCESS",
    "GOBP_REGULATION_OF_INTRACELLULAR_SIGNAL_TRANSDUCTION",
    "GOBP_REGULATION_OF_MULTICELLULAR_ORGANISMAL_DEVELOPMENT",
    "GOBP_REGULATION_OF_PHOSPHORUS_METABOLIC_PROCESS",
    "GOBP_REGULATION_OF_PROTEIN_MODIFICATION_PROCESS",
    "GOBP_REGULATION_OF_PROTEIN_PHOSPHORYLATION",
    "GOBP_REGULATION_OF_RESPONSE_TO_EXTERNAL_STIMULUS",
    "GOBP_REGULATION_OF_RESPONSE_TO_STRESS",
    "GOBP_REGULATION_OF_TRANSPORT",
    "GOBP_REPRODUCTION",
    "GOBP_RESPONSE_TO_ABIOTIC_STIMULUS",
    "GOBP_RESPONSE_TO_CYTOKINE",
    "GOBP_RESPONSE_TO_ENDOGENOUS_STIMULUS",
    "GOBP_RESPONSE_TO_LIPID",
    "GOBP_RESPONSE_TO_OXYGEN_CONTAINING_COMPOUND",
    "GOBP_SMALL_MOLECULE_METABOLIC_PROCESS",
    "GOBP_TISSUE_DEVELOPMENT",
    "GOBP_TRANSMEMBRANE_TRANSPORT",
    "GOBP_TUBE_DEVELOPMENT",
    "GOBP_TUBE_MORPHOGENESIS",
    "GOBP_VASCULATURE_DEVELOPMENT",
    "GOBP_VESICLE_MEDIATED_TRANSPORT",
    "GOCC_CELL_SURFACE",
    "GOCC_ENDOPLASMIC_RETICULUM",
    "GOCC_GOLGI_APPARATUS",
    "GOCC_INTRINSIC_COMPONENT_OF_PLASMA_MEMBRANE",
    "GOCC_PLASMA_MEMBRANE_REGION",
    "GOMF_IDENTICAL_PROTEIN_BINDING",
    "GOMF_MOLECULAR_FUNCTION_REGULATOR",
    "GOMF_MOLECULAR_TRANSDUCER_ACTIVITY",
    "GOMF_PROTEIN_CONTAINING_COMPLEX_BINDING",
    "GOMF_SEQUENCE_SPECIFIC_DNA_BINDING",
    "GOMF_SIGNALING_RECEPTOR_BINDING",
    "GOMF_TRANSCRIPTION_REGULATOR_ACTIVITY",
    "HP_ABNORMAL_RESPIRATORY_SYSTEM_MORPHOLOGY"
]

In [11]:
# columns_to_consider = ['gene_sequence'] + list(cells_features.columns[103:])
if dataset == 'ms':
    columns_to_consider = ['gene_sequence'] + features_ms
else:
    columns_to_consider = ['gene_sequence'] + features_pancreas
    
print(len(columns_to_consider))

99

In [12]:
# Filtering the dataframe to only include these columns
filtered_cells = cells_features[columns_to_consider]

In [13]:
print('Shape:', filtered_cells.shape)
filtered_cells.head()

Shape: (499, 99)

,gene_sequence,DESCARTES_FETAL_CEREBELLUM_VASCULAR_ENDOTHELIAL_CELLS,GAO_LARGE_INTESTINE_ADULT_CJ_IMMUNE_CELLS,HAY_BONE_MARROW_STROMAL,MANNO_MIDBRAIN_NEUROTYPES_HENDO,MANNO_MIDBRAIN_NEUROTYPES_HMGL,MANNO_MIDBRAIN_NEUROTYPES_HPERIC,MURARO_PANCREAS_ACINAR_CELL,MURARO_PANCREAS_DUCTAL_CELL,MURARO_PANCREAS_MESENCHYMAL_STROMAL_CELL,...,GOCC_INTRINSIC_COMPONENT_OF_PLASMA_MEMBRANE,GOCC_PLASMA_MEMBRANE_REGION,GOMF_IDENTICAL_PROTEIN_BINDING,GOMF_MOLECULAR_FUNCTION_REGULATOR,GOMF_MOLECULAR_TRANSDUCER_ACTIVITY,GOMF_PROTEIN_CONTAINING_COMPLEX_BINDING,GOMF_SEQUENCE_SPECIFIC_DNA_BINDING,GOMF_SIGNALING_RECEPTOR_BINDING,GOMF_TRANSCRIPTION_REGULATOR_ACTIVITY,HP_ABNORMAL_RESPIRATORY_SYSTEM_MORPHOLOGY
0,"<cls>,TXLNA,ATP2A3,ZNF141,CCDC141,SLC25A37,STO...","0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,...","0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,...","0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,...","0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,...","0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,...","0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,...","0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,1,1,1,1,0,0,1,...","0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,...",...,"0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,...","0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,...","0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,...","0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,1,0,0,1,...","0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,...","0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,..."
1,"<cls>,DSG2,TMEM144,TNFRSF1B,FKBP11,MUC20,DCN,A...","0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,...","0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,...","0,0,0,1,0,0,0,1,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,...","0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...","0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,...","0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,1,0,0,1,0,0,0,0,...","0,1,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,...","0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,...",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,...","0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,...","0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,...","0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,...","0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,...","0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,1,0,0,...","0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,..."
2,"<cls>,CNN2,LRAT,ACTN1,PLD6,PHLDB2,PIGA,CES2,MY...","0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,...","0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,...","0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...","0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,...","0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,...","0,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,...",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,...","0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,...","0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,..."
3,"<cls>,NINJ1,TNS3,SLC6A6,PGM2L1,CABYR,SLC3A1,SE...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...","0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,...","0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,...","0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,0,1,0,...","0,0,0,0,1,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,...","0,1,1,0,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,...","0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,1,0,...",...,"0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,...","0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,1,1,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,...","0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,..."
4,"<cls>,TMBIM1,SNAI1,LMCD1,ZNF347,KCNJ2,NID1,UPK...","0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...","0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,...","0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...","0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,...","0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,...","0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,...","0,1,0,0,0,0,0,1,1,0,0,1,0,1,0,0,0,1,1,0,0,0,0,...","0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,...",...,"0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0,0,1,1,0,0,0,0,...","0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,...","0,0,0,0,0,1,0,0,1,1,0,0,0,1,0,1,0,0,0,0,0,0,1,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,...","0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,...","0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,...","0,0,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,...","0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,..."

In [14]:
# Export compiled_cells_all-features.csv
num_col = filtered_cells.shape[1]
filtered_cells_path = os.path.join(data_dir, f'filt_features_{num_col}.csv')
filtered_cells.to_csv(filtered_cells_path, index=False, sep=';')

In [15]:
# Extract the column names directly
old_col = list(filtered_cells.columns)
# Create a new DataFrame with these column names as row values in a single column
rename_df = pd.DataFrame(old_col, columns=['old_col'])
# Display the first few rows of the new DataFrame
rename_df.head()

                                             old_col
0                                      gene_sequence
1  DESCARTES_FETAL_CEREBELLUM_VASCULAR_ENDOTHELIA...
2          GAO_LARGE_INTESTINE_ADULT_CJ_IMMUNE_CELLS
3                            HAY_BONE_MARROW_STROMAL
4                    MANNO_MIDBRAIN_NEUROTYPES_HENDO

In [16]:
import os
# Open new column names

col_df_path = os.path.join(data_dir, f'column_names_final.csv')
col_df = pd.read_csv(col_df_path)
col_df.head(10)

,old_col,new_col
0,gene_sequence,gene_sequence
1,DESCARTES_FETAL_CEREBELLUM_VASCULAR_ENDOTHELIA...,fetal cerebellum vascular endothelial cells
2,GAO_LARGE_INTESTINE_ADULT_CJ_IMMUNE_CELLS,large intestine adult immune cells
3,HAY_BONE_MARROW_STROMAL,bone marrow stromal
4,MANNO_MIDBRAIN_NEUROTYPES_HENDO,midbrain neurotype human endothelial cell
5,MANNO_MIDBRAIN_NEUROTYPES_HMGL,midbrain neurotypes human microglial cell
6,MANNO_MIDBRAIN_NEUROTYPES_HPERIC,midbrain neurotype human pericyte
7,MURARO_PANCREAS_ACINAR_CELL,pancreas acinar cell
8,MURARO_PANCREAS_DUCTAL_CELL,pancreas ductal cell
9,MURARO_PANCREAS_MESENCHYMAL_STROMAL_CELL,pancreas mesenchymal stromal cell

In [17]:
filtered_cells.rename(columns=dict(zip(col_df['old_col'], col_df['new_col'])), inplace=True)
filtered_cells.head()

/var/folders/y_/n7t8whz54_q5s7xfy2s01ypw0000gn/T/ipykernel_36898/2923648683.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_cells.rename(columns=dict(zip(col_df['old_col'], col_df['new_col'])), inplace=True)

,gene_sequence,fetal cerebellum vascular endothelial cells,large intestine adult immune cells,bone marrow stromal,midbrain neurotype human endothelial cell,midbrain neurotypes human microglial cell,midbrain neurotype human pericyte,pancreas acinar cell,pancreas ductal cell,pancreas mesenchymal stromal cell,...,GOCC intrinsic component of plasma membrane,GOCC plasma membrane region,GOMF identical protein binding,GOMF molecular function regulator,GOMF molecular transducer activity,GOMF protein containing complex binding,GOMF sequence specific DNA binding,GOMF signaling receptor binding,GOMF transcription regulator activity,abnormal respiratory system morphology
0,"<cls>,TXLNA,ATP2A3,ZNF141,CCDC141,SLC25A37,STO...","0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,...","0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,...","0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,...","0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,...","0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,...","0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,...","0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,1,1,1,1,1,0,0,1,...","0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,...",...,"0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,...","0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,...","0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,...","0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,1,0,0,1,...","0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,...","0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,..."
1,"<cls>,DSG2,TMEM144,TNFRSF1B,FKBP11,MUC20,DCN,A...","0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,1,0,0,0,...","0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,...","0,0,0,1,0,0,0,1,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,...","0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...","0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,...","0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,1,0,0,1,0,0,0,0,...","0,1,0,1,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,1,...","0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,...",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,...","0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,...","0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,...","0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,...","0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,...","0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,1,0,0,...","0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,..."
2,"<cls>,CNN2,LRAT,ACTN1,PLD6,PHLDB2,PIGA,CES2,MY...","0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,...","0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,...","0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...","0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,...","0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,1,...","0,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,...",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,...","0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,...","0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,..."
3,"<cls>,NINJ1,TNS3,SLC6A6,PGM2L1,CABYR,SLC3A1,SE...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,...","0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,1,0,0,1,0,...","0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,...","0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,1,0,1,0,0,1,0,...","0,0,0,0,1,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,...","0,1,1,0,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,...","0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,1,1,1,0,0,1,0,...",...,"0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,...","0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,1,1,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,...","0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,..."
4,"<cls>,TMBIM1,SNAI1,LMCD1,ZNF347,KCNJ2,NID1,UPK...","0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...","0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,...","0,1,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,...","0,1,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,...","0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,...","0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,...","0,1,0,0,0,0,0,1,1,0,0,1,0,1,0,0,0,1,1,0,0,0,0,...","0,0,1,1,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,...",...,"0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0,0,1,1,0,0,0,0,...","0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,...","0,0,0,0,0,1,0,0,1,1,0,0,0,1,0,1,0,0,0,0,0,0,1,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,...","0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,...","0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,...","0,0,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,...","0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,..."

In [18]:
# Merge the DataFrames on the 'gene_sequence' column
num_col = len(columns_to_consider)
print('Number of Features:', num_col)
merge_filtered_cells = pd.merge(compiled_cells, filtered_cells, on='gene_sequence', how='inner')
merge_filtered_cells.head()

Number of Features: 99

,gene_sequence,label,expression,layer0_head0,layer0_head1,layer0_head2,layer0_head3,layer0_head4,layer0_head5,layer0_head6,...,GOCC intrinsic component of plasma membrane,GOCC plasma membrane region,GOMF identical protein binding,GOMF molecular function regulator,GOMF molecular transducer activity,GOMF protein containing complex binding,GOMF sequence specific DNA binding,GOMF signaling receptor binding,GOMF transcription regulator activity,abnormal respiratory system morphology
0,"<cls>,TXLNA,ATP2A3,ZNF141,CCDC141,SLC25A37,STO...",5,"0.0,48.0,33.0,25.0,5.0,3.0,10.0,28.0,5.0,29.0,...","0.0023745133,0.0032477628,0.003589545,0.003814...","0.0041318787,0.0053796424,0.0041540335,0.00306...","0.0056217974,0.0031721308,0.005039241,0.004776...","0.0034448185,0.0032406966,0.0040769065,0.00487...","0.0038653233,0.0041617695,0.0020131315,0.00385...","0.003914756,0.0034802882,0.005446018,0.0034722...","0.0042973505,0.0035008143,0.0028890239,0.00347...",...,"0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,...","0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,...","0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,...","0,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0,1,0,0,1,...","0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,...","0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,..."
1,"<cls>,DSG2,TMEM144,TNFRSF1B,FKBP11,MUC20,DCN,A...",5,"0.0,39.0,7.0,19.0,6.0,17.0,7.0,19.0,26.0,6.0,4...","0.0022430576,0.0024487586,0.003219843,0.003661...","0.004013164,0.0031627351,0.0036624381,0.003953...","0.0042283423,0.0031852438,0.004393687,0.002575...","0.0034300121,0.0023620245,0.0043808324,0.00346...","0.0032802566,0.0028360444,0.0044557275,0.00289...","0.004048269,0.0047665904,0.0038825262,0.003081...","0.0042852582,0.0031577605,0.0056061805,0.00359...",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,...","0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,...","0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,...","0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,...","0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,...","0,0,0,0,0,0,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,1,0,0,...","0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,..."
2,"<cls>,CNN2,LRAT,ACTN1,PLD6,PHLDB2,PIGA,CES2,MY...",5,"0.0,27.0,20.0,39.0,5.0,7.0,3.0,11.0,12.0,1.0,3...","0.0022238698,0.0040896675,0.004484682,0.002118...","0.0039243894,0.0040566986,0.0026453421,0.00478...","0.0048712324,0.0034570356,0.0030926508,0.00369...","0.003476348,0.0037290629,0.0028929042,0.004210...","0.003399026,0.0025909895,0.0042975056,0.004100...","0.004021946,0.002352441,0.0031674122,0.0027053...","0.0031837898,0.0027910753,0.0021618963,0.00399...",...,"0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,...","0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,...","0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,...","0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,..."
3,"<cls>,NINJ1,TNS3,SLC6A6,PGM2L1,CABYR,SLC3A1,SE...",5,"0.0,42.0,19.0,39.0,20.0,17.0,14.0,33.0,21.0,37...","0.0020445194,0.0031070835,0.0025515305,0.00327...","0.0040934836,0.0028073455,0.0034256505,0.00244...","0.0043800664,0.0029222732,0.0025062195,0.00437...","0.0034533436,0.0025593678,0.003978598,0.002954...","0.0038189043,0.0032943436,0.002777985,0.003936...","0.0036355853,0.0033676857,0.00409,0.0038118216...","0.0043353783,0.0040053073,0.002787665,0.002944...",...,"0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,...","0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,1,1,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,...","0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,...","0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,..."
4,"<cls>,TMBIM1,SNAI1,LMCD1,ZNF347,KCNJ2,NID1,UPK...",2,"0.0,5.0,23.0,42.0,26.0,39.0,28.0,28.0,28.0,16....","0.0021203735,0.002208613,0.0047930344,0.004826...","0.0040604477,0.0039716368,0.00493733,0.0033131...","0.005657586,0.003112157,0.0040237918,0.0037283...","0.003414135,0.0037594072,0.004144798,0.0034618...","0.003272853,0.0038072,0.0030302322,0.004112403...","0.0044797715,0.004235163,0.0032671287,0.003604...","0.0043147453,0.0030068154,0.002950847,0.006144...",...,"0,0,0,0,0,1,0,1,0,0,0,0,0,1,1,0,0,1,1,0,0,0,0,...","0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,...","0,0,0,0,0,1,0,0,1,1,0,0,0,1,0,1,0,0,0,0,0,0,1,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,...","0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...","0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,...","0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,...","0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,...","0,0,1,1,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,...","0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,..."

In [19]:
merge_filtered_cells.shape

(499, 201)

In [20]:
print(data_dir)
print(model)
print(num_col)

/Users/vivianschu/Documents/MBP/Lab/Genomic Interpretability/scgpt_attn_results/test/FINAL_LRP-attention/pancreas/random_init-2
random_init-2
99

In [21]:
final_df_path = os.path.join(data_dir, f'scgpt_{model}_{dataset}-features_{num_col}.csv')
print(final_df_path)
merge_filtered_cells.to_csv(final_df_path, index=False, sep=';')

/Users/vivianschu/Documents/MBP/Lab/Genomic Interpretability/scgpt_attn_results/test/FINAL_LRP-attention/pancreas/random_init-2/scgpt_random_init-2_pancreas-features_99.csv