# DNABERT Dataset Preparation

This notebook is demonstrates how to take the ensembl enhancer genomic_benchmarks dataset from Hugging Face and prepare specific datasets for use as input to DNABERT for the genome-head-interpreter project.

### Acquire data

In [1]:
!pip install -qq datasets

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 542.0/542.0 kB 5.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 5.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 4.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.8/134.8 kB 8.1 MB/s eta 0:00:00

Access the data using HuggingFace:

In [2]:
from huggingface_hub import notebook_login

notebook_login()

VBox(children=(HTML(value='<center> <img\nsrc=https://huggingface.co/front/assets/huggingface_logo-noborder.sv…

In [3]:
import pandas as pd

In [4]:
from datasets import Dataset
from datasets import load_dataset
from sklearn.utils import shuffle

In [5]:
dataset_human_enhancer = load_dataset('katarinagresova/Genomic_Benchmarks_human_enhancers_ensembl', use_auth_token=True)

/usr/local/lib/python3.10/dist-packages/datasets/load.py:2547: FutureWarning: 'use_auth_token' was deprecated in favor of 'token' in version 2.14.0 and will be removed in 3.0.0.
You can remove this warning by passing 'token=<use_auth_token>' instead.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:89: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

Downloading readme:   0%|          | 0.00/482 [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/16.4M [00:00<?, ?B/s]

Downloading data:   0%|          | 0.00/4.08M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/123872 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/30970 [00:00<?, ? examples/s]

In [6]:
dataset_human_enhancer

DatasetDict({
    train: Dataset({
        features: ['seq', 'label'],
        num_rows: 123872
    })
    test: Dataset({
        features: ['seq', 'label'],
        num_rows: 30970
    })
})

### Inspect data to see what must be done to prepare for DNABERT

In [7]:
def count_sequences_with_n(data):
    count = 0
    for seq in data['seq']:
        if 'N' in seq:
            count += 1
    return count

# count sequences with 'N' in the training dataset
train_count = count_sequences_with_n(dataset_human_enhancer['train'])
print(f"Number of sequences with 'N' in train dataset: {train_count}")

# count sequences with 'N' in the testing dataset
test_count = count_sequences_with_n(dataset_human_enhancer['test'])
print(f"Number of sequences with 'N' in test dataset: {test_count}")

Number of sequences with 'N' in train dataset: 66
Number of sequences with 'N' in test dataset: 10

In [8]:
# function to compute sequence length
def compute_seq_length(example):
    example['length'] = len(example['seq'])
    return example

Minimum length sequence in the dataset?

In [9]:
# apply the function to the train and test datasets for enhancer
train_dataset_enhancer = dataset_human_enhancer['train'].map(compute_seq_length)
test_dataset_enhancer = dataset_human_enhancer['test'].map(compute_seq_length)

# average sequence length
avg_train_length_enhancer = sum(train_dataset_enhancer['length']) / len(train_dataset_enhancer)
avg_test_length_enhancer = sum(test_dataset_enhancer['length']) / len(test_dataset_enhancer)

print(f"Average train sequence length: {avg_train_length_enhancer}")
print(f"Average test sequence length: {avg_test_length_enhancer}")

Map:   0%|          | 0/123872 [00:00<?, ? examples/s]

Map:   0%|          | 0/30970 [00:00<?, ? examples/s]

Average train sequence length: 269.1078532678894
Average test sequence length: 267.88931223764934

In [10]:
print(min(train_dataset_enhancer['length']))

2

### Prepare data for DNABERT

Prepare functions and imports we will need for filtering

In [11]:
def filter_seq_length(example):
    return (len(example['seq']) >= 50) and ('N' not in example['seq']) and (len(example['seq']) <= 510)

In [12]:
#Original DNABERT function:

def seq2kmer(seq, k):
    """
    Convert original sequence to kmers

    Arguments:
    seq -- str, original sequence.
    k -- int, kmer of length k specified.

    Returns:
    kmers -- str, kmers separated by space

    """
    kmer = [seq[x:x+k] for x in range(len(seq)+1-k)]
    kmers = " ".join(kmer)
    return kmers

In [13]:
import numpy as np

### Prepare enhancer

Filter the data to make sure there are no sequences less than 205 in length and also remove any sequences with "N" characters

In [14]:
# filter the datasets
filtered_train_dataset_enhancer = dataset_human_enhancer['train'].filter(filter_seq_length)
filtered_test_dataset_enhancer = dataset_human_enhancer['test'].filter(filter_seq_length)

Filter:   0%|          | 0/123872 [00:00<?, ? examples/s]

Filter:   0%|          | 0/30970 [00:00<?, ? examples/s]

In [15]:
# apply the function to the filtered datasets
filtered_train_dataset_enhancer = filtered_train_dataset_enhancer.map(compute_seq_length)
filtered_test_dataset_enhancer = filtered_test_dataset_enhancer.map(compute_seq_length)

# average sequence length
avg_filtered_train_length_enhancer = sum(filtered_train_dataset_enhancer['length']) / len(filtered_train_dataset_enhancer)
avg_filtered_test_length_enhancer = sum(filtered_test_dataset_enhancer['length']) / len(filtered_test_dataset_enhancer)

print(f"Average filtered train sequence length: {avg_filtered_train_length_enhancer}")
print(f"Average filtered test sequence length: {avg_filtered_test_length_enhancer}")

Map:   0%|          | 0/115595 [00:00<?, ? examples/s]

Map:   0%|          | 0/28941 [00:00<?, ? examples/s]

Average filtered train sequence length: 271.1897573424456
Average filtered test sequence length: 270.7583013717563

In [16]:
# count sequences with 'N' in the training dataset after filtering...
train_count = count_sequences_with_n(filtered_train_dataset_enhancer)
print(f"Number of sequences with 'N' in train dataset: {train_count}")

# count sequences with 'N' in the testing dataset after filtering...
test_count = count_sequences_with_n(filtered_test_dataset_enhancer)
print(f"Number of sequences with 'N' in test dataset: {test_count}")

Number of sequences with 'N' in train dataset: 0
Number of sequences with 'N' in test dataset: 0

Confirm filtering:

In [18]:
print(min(filtered_train_dataset_enhancer['length']))
print(min(filtered_test_dataset_enhancer['length']))

50
50

In [20]:
print(max(filtered_train_dataset_enhancer['length']))
print(max(filtered_test_dataset_enhancer['length']))

510
510

Make the datasets by k-merizing using DNABERT k-merizing function, given the new filtering for sequences without "N" nucleotides and with sequence length >= 50 and =< 510:

In [21]:
train_human_enhancer = pd.DataFrame({"label": filtered_train_dataset_enhancer["label"]})
train_human_enhancer['sequence']= [seq2kmer(item, 6) for item in filtered_train_dataset_enhancer["seq"]]
test_human_enhancer = pd.DataFrame({"label": filtered_test_dataset_enhancer["label"]})
test_human_enhancer['sequence'] = [seq2kmer(item, 6) for item in filtered_test_dataset_enhancer["seq"]]

In [22]:
test_human_enhancer = shuffle(test_human_enhancer)
train_human_enhancer = shuffle(train_human_enhancer)

In [23]:
train_human_enhancer

        label                                           sequence
83233       1  GTGCAG TGCAGA GCAGAA CAGAAA AGAAAG GAAAGA AAAG...
54562       0  TGGGGG GGGGGC GGGGCA GGGCAG GGCAGG GCAGGG CAGG...
56087       0  GCAAAC CAAACA AAACAT AACATT ACATTA CATTAA ATTA...
108621      1  TGAGTG GAGTGG AGTGGG GTGGGT TGGGTG GGGTGC GGTG...
7541        0  GGAGTA GAGTAG AGTAGA GTAGAA TAGAAT AGAATT GAAT...
...       ...                                                ...
96420       1  TGTTTT GTTTTT TTTTTG TTTTGA TTTGAA TTGAAG TGAA...
111689      1  TGAAAT GAAATA AAATAC AATACT ATACTG TACTGA ACTG...
24879       0  CCTGCT CTGCTC TGCTCT GCTCTC CTCTCT TCTCTG CTCT...
92206       1  GTAAAA TAAAAA AAAAAA AAAAAA AAAAAA AAAAAA AAAA...
28956       0  TTTTAT TTTATC TTATCA TATCAT ATCATT TCATTC CATT...

[115595 rows x 2 columns]

In [24]:
test_human_enhancer

       label                                           sequence
20622      1  GGGGAT GGGATC GGATCT GATCTG ATCTGT TCTGTT CTGT...
2851       0  TGCCAG GCCAGT CCAGTT CAGTTC AGTTCC GTTCCT TTCC...
20030      1  CCACTT CACTTC ACTTCC CTTCCA TTCCAA TCCAAC CCAA...
19729      1  TGGCGG GGCGGT GCGGTG CGGTGC GGTGCA GTGCAG TGCA...
27326      1  TCTCTG CTCTGT TCTGTT CTGTTT TGTTTT GTTTTT TTTT...
...      ...                                                ...
15162      1  TGAGGA GAGGAG AGGAGC GGAGCT GAGCTT AGCTTG GCTT...
17574      1  GACTTG ACTTGG CTTGGG TTGGGG TGGGGT GGGGTG GGGT...
26804      1  TGAATC GAATCC AATCCA ATCCAG TCCAGC CCAGCA CAGC...
2429       0  TTACTG TACTGG ACTGGC CTGGCT TGGCTC GGCTCC GCTC...
2271       0  GGAGCC GAGCCC AGCCCT GCCCTT CCCTTC CCTTCC CTTC...

[28941 rows x 2 columns]

Put in the format DNABERT expects:

In [25]:
test_human_enhancer.index = test_human_enhancer.sequence

In [26]:
test_human_enhancer.drop('sequence', axis=1, inplace=True)

In [27]:
test_human_enhancer

                                                    label
sequence
GGGGAT GGGATC GGATCT GATCTG ATCTGT TCTGTT CTGTT...      1
TGCCAG GCCAGT CCAGTT CAGTTC AGTTCC GTTCCT TTCCT...      0
CCACTT CACTTC ACTTCC CTTCCA TTCCAA TCCAAC CCAAC...      1
TGGCGG GGCGGT GCGGTG CGGTGC GGTGCA GTGCAG TGCAG...      1
TCTCTG CTCTGT TCTGTT CTGTTT TGTTTT GTTTTT TTTTT...      1
...                                                   ...
TGAGGA GAGGAG AGGAGC GGAGCT GAGCTT AGCTTG GCTTG...      1
GACTTG ACTTGG CTTGGG TTGGGG TGGGGT GGGGTG GGGTG...      1
TGAATC GAATCC AATCCA ATCCAG TCCAGC CCAGCA CAGCA...      1
TTACTG TACTGG ACTGGC CTGGCT TGGCTC GGCTCC GCTCC...      0
GGAGCC GAGCCC AGCCCT GCCCTT CCCTTC CCTTCC CTTCC...      0

[28941 rows x 1 columns]

In [28]:
train_human_enhancer.index = train_human_enhancer.sequence

In [29]:
train_human_enhancer.drop('sequence', axis=1, inplace=True)

In [30]:
train_human_enhancer

                                                    label
sequence
GTGCAG TGCAGA GCAGAA CAGAAA AGAAAG GAAAGA AAAGA...      1
TGGGGG GGGGGC GGGGCA GGGCAG GGCAGG GCAGGG CAGGG...      0
GCAAAC CAAACA AAACAT AACATT ACATTA CATTAA ATTAA...      0
TGAGTG GAGTGG AGTGGG GTGGGT TGGGTG GGGTGC GGTGC...      1
GGAGTA GAGTAG AGTAGA GTAGAA TAGAAT AGAATT GAATT...      0
...                                                   ...
TGTTTT GTTTTT TTTTTG TTTTGA TTTGAA TTGAAG TGAAG...      1
TGAAAT GAAATA AAATAC AATACT ATACTG TACTGA ACTGA...      1
CCTGCT CTGCTC TGCTCT GCTCTC CTCTCT TCTCTG CTCTG...      0
GTAAAA TAAAAA AAAAAA AAAAAA AAAAAA AAAAAA AAAAA...      1
TTTTAT TTTATC TTATCA TATCAT ATCATT TCATTC CATTC...      0

[115595 rows x 1 columns]

In [31]:
# distribution of labels
df = train_human_enhancer
label_distribution = df['label'].value_counts()

In [32]:
(label_distribution)

label
1    57827
0    57768
Name: count, dtype: int64

In [33]:
# distribution of labels
df = test_human_enhancer
label_distribution = df['label'].value_counts()

In [34]:
(label_distribution)

label
1    14475
0    14466
Name: count, dtype: int64

In [ ]:
# saving as tsv file
train_human_enhancer.to_csv('train.tsv', sep="\t")

In [ ]:
# saving as tsv file
test_human_enhancer.to_csv('dev.tsv', sep="\t")